name: SCA

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      username:
        required: false
        type: string
    secrets:
      token:
        required: false
  schedule:
    - cron: '16 2 * * 4'

jobs:
  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
                
      - name: dotnet SCA
        run: |
          dotnet tool restore
          dotnet run --project ./build/build.fsproj -c Release -t SCA
          